import type { UiLocale } from "./index";

const COPY = {
  en: { store: "Store", today: "Today", schedule: "Schedule", analysis: "Analysis", title: "Store master", subtitle: "Operational settings and cost inputs", basic: "Basic info", menu: "Menu", inventory: "Ingredients · Inventory", suppliers: "Suppliers", costs: "Rent · Fixed costs", view: "View", edit: "Edit", review: "Review changes", save: "Save", cancel: "Cancel", signIn: "Owner sign in", signOut: "Sign out", email: "Email", password: "Password", authRequired: "Owner authentication is required to edit.", saved: "Store settings saved.", name: "Store name", hours: "Opening hours", closed: "Closed", laborTarget: "Target labor ratio", foodTarget: "Target food-cost ratio", price: "Price", category: "Category", active: "Active", recipe: "Recipe", quantity: "Quantity", unit: "Unit", onHand: "On hand", lastCost: "Last purchase cost", par: "Par level", reorder: "Reorder point", lead: "Lead time (days)", supplier: "Supplier", rent: "Monthly base rent", fees: "Monthly occupancy fees", utilities: "Utilities", software: "Software · security · rentals", marketing: "Marketing", other: "Other fixed", packaging: "Packaging · consumables", processing: "Payment processing", delivery: "Delivery · marketplace", readOnly: "Recorded actuals remain read-only.", reviewHelp: "Review the exact operational inputs before saving.", empty: "No records", pnl: "Operating P&L", sales: "Sales", food: "Direct food cost", labor: "Scheduled base wage", variable: "Variable operating costs", occupancy: "Occupancy", fixed: "Other fixed costs", profit: "Estimated operating profit", margin: "Operating margin", bep: "Break-even sales", fl: "Food + labor ratio" },
  ko: { store: "매장", today: "오늘", schedule: "스케줄", analysis: "분석", title: "매장 기준 정보", subtitle: "운영 설정과 비용 입력", basic: "기본 정보", menu: "메뉴", inventory: "식재료 · 재고", suppliers: "공급업체", costs: "임차 · 고정비", view: "보기", edit: "수정", review: "변경 검토", save: "저장", cancel: "취소", signIn: "소유자 로그인", signOut: "로그아웃", email: "이메일", password: "비밀번호", authRequired: "수정하려면 소유자 인증이 필요합니다.", saved: "매장 설정을 저장했습니다.", name: "매장명", hours: "영업시간", closed: "휴무", laborTarget: "목표 인건비율", foodTarget: "목표 식재료비율", price: "판매가", category: "분류", active: "판매", recipe: "레시피", quantity: "수량", unit: "단위", onHand: "현재고", lastCost: "최근 매입 단가", par: "적정 재고", reorder: "재주문점", lead: "리드타임(일)", supplier: "공급업체", rent: "월 기본 임차료", fees: "월 관리·부대비", utilities: "공과금", software: "소프트웨어 · 보안 · 대여", marketing: "마케팅", other: "기타 고정비", packaging: "포장 · 소모품", processing: "결제 처리", delivery: "배달 · 플랫폼", readOnly: "기록된 실적 데이터는 읽기 전용으로 유지됩니다.", reviewHelp: "저장 전에 변경할 운영 입력값을 정확히 확인하세요.", empty: "내역 없음", pnl: "운영 손익", sales: "매출", food: "직접 식재료비", labor: "예상 스케줄 임금", variable: "변동 운영비", occupancy: "임차비", fixed: "기타 고정비", profit: "추정 운영이익", margin: "운영이익률", bep: "손익분기 매출", fl: "식재료비 + 인건비율" },
  ja: { store: "店舗", today: "今日", schedule: "スケジュール", analysis: "分析", title: "店舗マスター", subtitle: "運営設定とコスト入力", basic: "基本情報", menu: "メニュー", inventory: "食材・在庫", suppliers: "仕入先", costs: "賃料・固定費", view: "表示", edit: "編集", review: "変更を確認", save: "保存", cancel: "キャンセル", signIn: "オーナーログイン", signOut: "ログアウト", email: "メール", password: "パスワード", authRequired: "編集にはオーナー認証が必要です。", saved: "店舗設定を保存しました。", name: "店舗名", hours: "営業時間", closed: "休業", laborTarget: "目標人件費率", foodTarget: "目標食材原価率", price: "販売価格", category: "分類", active: "販売中", recipe: "レシピ", quantity: "数量", unit: "単位", onHand: "現在庫", lastCost: "直近仕入単価", par: "適正在庫", reorder: "発注点", lead: "リードタイム（日）", supplier: "仕入先", rent: "月額基本賃料", fees: "月額共益費", utilities: "光熱費", software: "ソフト・警備・レンタル", marketing: "マーケティング", other: "その他固定費", packaging: "包装・消耗品", processing: "決済手数料", delivery: "デリバリー・モール", readOnly: "記録済み実績は読み取り専用です。", reviewHelp: "保存前に運営入力を確認してください。", empty: "データなし", pnl: "営業損益", sales: "売上", food: "直接食材費", labor: "予定シフト賃金", variable: "変動運営費", occupancy: "賃借費", fixed: "その他固定費", profit: "推定営業利益", margin: "営業利益率", bep: "損益分岐売上", fl: "食材費＋人件費率" },
  es: { store: "Tienda", today: "Hoy", schedule: "Horario", analysis: "Análisis", title: "Datos maestros", subtitle: "Configuración operativa y costes", basic: "Información básica", menu: "Menú", inventory: "Ingredientes · Inventario", suppliers: "Proveedores", costs: "Alquiler · Costes fijos", view: "Ver", edit: "Editar", review: "Revisar cambios", save: "Guardar", cancel: "Cancelar", signIn: "Acceso del propietario", signOut: "Cerrar sesión", email: "Correo", password: "Contraseña", authRequired: "Se requiere autenticación del propietario para editar.", saved: "Configuración guardada.", name: "Nombre del local", hours: "Horario de apertura", closed: "Cerrado", laborTarget: "Objetivo de mano de obra", foodTarget: "Objetivo de coste alimentario", price: "Precio", category: "Categoría", active: "Activo", recipe: "Receta", quantity: "Cantidad", unit: "Unidad", onHand: "Existencias", lastCost: "Último coste de compra", par: "Nivel par", reorder: "Punto de reposición", lead: "Plazo (días)", supplier: "Proveedor", rent: "Alquiler base mensual", fees: "Gastos mensuales", utilities: "Suministros", software: "Software · seguridad · alquileres", marketing: "Marketing", other: "Otros fijos", packaging: "Envases · consumibles", processing: "Procesamiento de pagos", delivery: "Entrega · plataformas", readOnly: "Los datos reales registrados siguen siendo de solo lectura.", reviewHelp: "Revisa las entradas operativas exactas antes de guardar.", empty: "Sin datos", pnl: "Pérdidas y ganancias operativas", sales: "Ventas", food: "Coste directo de alimentos", labor: "Salario programado estimado", variable: "Costes operativos variables", occupancy: "Ocupación", fixed: "Otros costes fijos", profit: "Beneficio operativo estimado", margin: "Margen operativo", bep: "Ventas de equilibrio", fl: "Ratio alimentos + mano de obra" },
  "zh-CN": { store: "门店", today: "今日", schedule: "排班", analysis: "分析", title: "门店主数据", subtitle: "运营设置与成本输入", basic: "基本信息", menu: "菜单", inventory: "食材与库存", suppliers: "供应商", costs: "租金与固定成本", view: "查看", edit: "编辑", review: "审核更改", save: "保存", cancel: "取消", signIn: "店主登录", signOut: "退出登录", email: "邮箱", password: "密码", authRequired: "编辑需要店主身份验证。", saved: "门店设置已保存。", name: "门店名称", hours: "营业时间", closed: "休息", laborTarget: "目标人工成本率", foodTarget: "目标食材成本率", price: "售价", category: "分类", active: "启用", recipe: "配方", quantity: "数量", unit: "单位", onHand: "现有库存", lastCost: "最近采购单价", par: "标准库存", reorder: "补货点", lead: "提前期（天）", supplier: "供应商", rent: "月基础租金", fees: "月占用费用", utilities: "水电费", software: "软件·安保·租赁", marketing: "营销", other: "其他固定成本", packaging: "包装·耗材", processing: "支付处理", delivery: "配送·平台", readOnly: "已记录的实际数据保持只读。", reviewHelp: "保存前请核对准确的运营输入。", empty: "暂无记录", pnl: "运营损益", sales: "销售额", food: "直接食材成本", labor: "预计排班工资", variable: "可变运营成本", occupancy: "租赁成本", fixed: "其他固定成本", profit: "预计运营利润", margin: "运营利润率", bep: "盈亏平衡销售额", fl: "食材+人工成本率" },
} as const;

export function getStoreSurfaceCopy(locale: UiLocale) {
  return COPY[locale];
}
