-- OwnerOps Store SSOT / Reference Cache
-- Target: PostgreSQL / Supabase
-- Principle: store actuals are truth; public market data is reference evidence only.

create extension if not exists pgcrypto;

create or replace function public.oo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Store / operating settings
-- ---------------------------------------------------------------------------
create table if not exists public.oo_stores (
  id text primary key,
  name text not null,
  industry text not null,
  market_id text not null,
  country_code text not null,
  city_name text not null,
  currency_code text not null,
  timezone text not null,
  opening_hours jsonb not null default '{}'::jsonb,
  targets jsonb not null default '{}'::jsonb,
  policies jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists oo_stores_touch on public.oo_stores;
create trigger oo_stores_touch before update on public.oo_stores
for each row execute function public.oo_touch_updated_at();

create table if not exists public.oo_occupancy_costs (
  store_id text primary key references public.oo_stores(id) on delete cascade,
  base_rent_monthly numeric(14,2) not null default 0,
  recurring_fees_monthly numeric(14,2) not null default 0,
  deposit numeric(14,2),
  lease_start date,
  lease_end date,
  next_escalation_date date,
  next_escalation_rate numeric(8,5),
  updated_at timestamptz not null default now()
);

drop trigger if exists oo_occupancy_touch on public.oo_occupancy_costs;
create trigger oo_occupancy_touch before update on public.oo_occupancy_costs
for each row execute function public.oo_touch_updated_at();

create table if not exists public.oo_operating_costs (
  store_id text primary key references public.oo_stores(id) on delete cascade,
  packaging_consumables_rate numeric(8,5) not null default 0,
  payment_processing_rate numeric(8,5) not null default 0,
  delivery_marketplace_rate numeric(8,5) not null default 0,
  utilities_monthly numeric(14,2) not null default 0,
  software_security_rentals_monthly numeric(14,2) not null default 0,
  marketing_monthly numeric(14,2) not null default 0,
  other_fixed_monthly numeric(14,2) not null default 0,
  updated_at timestamptz not null default now()
);

drop trigger if exists oo_operating_costs_touch on public.oo_operating_costs;
create trigger oo_operating_costs_touch before update on public.oo_operating_costs
for each row execute function public.oo_touch_updated_at();

-- ---------------------------------------------------------------------------
-- People / schedule / attendance
-- ---------------------------------------------------------------------------
create table if not exists public.oo_workers (
  store_id text not null references public.oo_stores(id) on delete cascade,
  worker_id text not null,
  name text not null,
  display_name text,
  contact_label text,
  employment_type text not null,
  role text not null,
  skills jsonb not null default '[]'::jsonb,
  hourly_rate numeric(12,4) not null,
  preferred_weekly_hours numeric(8,2),
  max_weekly_hours numeric(8,2),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (store_id, worker_id)
);

drop trigger if exists oo_workers_touch on public.oo_workers;
create trigger oo_workers_touch before update on public.oo_workers
for each row execute function public.oo_touch_updated_at();

create table if not exists public.oo_worker_availability_rules (
  id bigint generated by default as identity primary key,
  store_id text not null,
  worker_id text not null,
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  available boolean not null default true,
  foreign key (store_id, worker_id) references public.oo_workers(store_id, worker_id) on delete cascade,
  check (end_time > start_time)
);

create table if not exists public.oo_worker_availability_exceptions (
  id text primary key,
  store_id text not null,
  worker_id text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  available boolean not null,
  reason text,
  source text not null,
  created_at timestamptz not null default now(),
  foreign key (store_id, worker_id) references public.oo_workers(store_id, worker_id) on delete cascade,
  check (ends_at > starts_at)
);

create table if not exists public.oo_shifts (
  store_id text not null references public.oo_stores(id) on delete cascade,
  shift_id text not null,
  worker_id text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  role text not null,
  required_skills jsonb not null default '[]'::jsonb,
  status text not null,
  published boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (store_id, shift_id),
  foreign key (store_id, worker_id) references public.oo_workers(store_id, worker_id) on delete set null,
  check (ends_at > starts_at)
);

create index if not exists oo_shifts_store_starts_idx on public.oo_shifts(store_id, starts_at);

create table if not exists public.oo_time_entries (
  id text primary key,
  store_id text not null,
  worker_id text not null,
  shift_id text,
  clock_in timestamptz not null,
  clock_out timestamptz,
  source text not null,
  created_at timestamptz not null default now(),
  foreign key (store_id, worker_id) references public.oo_workers(store_id, worker_id) on delete cascade,
  foreign key (store_id, shift_id) references public.oo_shifts(store_id, shift_id) on delete set null
);

create table if not exists public.oo_incidents (
  id text primary key,
  store_id text not null references public.oo_stores(id) on delete cascade,
  type text not null,
  status text not null,
  created_at timestamptz not null,
  resolved_at timestamptz,
  worker_id text,
  shift_id text,
  inventory_item_id text,
  reason text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists oo_incidents_store_status_idx on public.oo_incidents(store_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- Sales / tasks / operating log
-- ---------------------------------------------------------------------------
create table if not exists public.oo_sales_snapshots (
  id text primary key,
  store_id text not null references public.oo_stores(id) on delete cascade,
  business_date date not null,
  hour smallint,
  gross_sales numeric(14,2) not null,
  net_sales numeric(14,2) not null,
  order_count integer not null,
  source text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.oo_sales_items (
  sales_snapshot_id text not null references public.oo_sales_snapshots(id) on delete cascade,
  menu_item_id text not null,
  quantity numeric(12,3) not null,
  net_sales numeric(14,2) not null,
  primary key (sales_snapshot_id, menu_item_id)
);

create table if not exists public.oo_tasks (
  id text primary key,
  store_id text not null references public.oo_stores(id) on delete cascade,
  title text not null,
  due_at timestamptz,
  shift_id text,
  worker_id text,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists oo_tasks_touch on public.oo_tasks;
create trigger oo_tasks_touch before update on public.oo_tasks
for each row execute function public.oo_touch_updated_at();

create table if not exists public.oo_store_log (
  id text primary key,
  store_id text not null references public.oo_stores(id) on delete cascade,
  created_at timestamptz not null,
  type text not null,
  summary text not null,
  related_ids jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

-- ---------------------------------------------------------------------------
-- Ingredient / procurement / inventory / Prep / Menu BOM
-- ---------------------------------------------------------------------------
create table if not exists public.oo_ingredients (
  ingredient_id text primary key,
  canonical_name text not null,
  name_ko text,
  name_en text,
  category text not null,
  base_unit text not null,
  storage_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists oo_ingredients_touch on public.oo_ingredients;
create trigger oo_ingredients_touch before update on public.oo_ingredients
for each row execute function public.oo_touch_updated_at();

create table if not exists public.oo_ingredient_aliases (
  id bigint generated by default as identity primary key,
  ingredient_id text not null references public.oo_ingredients(ingredient_id) on delete cascade,
  market_id text,
  locale text,
  alias text not null,
  source_id text,
  unique (ingredient_id, market_id, locale, alias)
);

create index if not exists oo_ingredient_aliases_alias_idx on public.oo_ingredient_aliases(lower(alias));

create table if not exists public.oo_yield_benchmarks (
  id bigint generated by default as identity primary key,
  ingredient_id text references public.oo_ingredients(ingredient_id) on delete cascade,
  market_id text,
  material_label text not null,
  procurement_form text not null,
  use_form text not null,
  yield_rate numeric(8,5) not null check (yield_rate > 0 and yield_rate <= 1),
  source_label text not null,
  source_url text,
  confidence numeric(5,4) not null default 0.7,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.oo_suppliers (
  store_id text not null references public.oo_stores(id) on delete cascade,
  supplier_id text not null,
  name text not null,
  contact_label text,
  default_lead_time_days integer not null default 1,
  active boolean not null default true,
  primary key (store_id, supplier_id)
);

create table if not exists public.oo_inventory_items (
  store_id text not null references public.oo_stores(id) on delete cascade,
  item_id text not null,
  ingredient_id text references public.oo_ingredients(ingredient_id),
  name text not null,
  category text not null,
  base_unit text not null,
  purchase_form text not null default 'as_purchased',
  store_yield_rate numeric(8,5) check (store_yield_rate is null or (store_yield_rate > 0 and store_yield_rate <= 1)),
  on_hand numeric(14,4) not null default 0,
  par_level numeric(14,4) not null default 0,
  reorder_point numeric(14,4) not null default 0,
  lead_time_days integer not null default 1,
  supplier_id text,
  market_reference_key text,
  perishable boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (store_id, item_id),
  foreign key (store_id, supplier_id) references public.oo_suppliers(store_id, supplier_id) on delete set null
);

drop trigger if exists oo_inventory_items_touch on public.oo_inventory_items;
create trigger oo_inventory_items_touch before update on public.oo_inventory_items
for each row execute function public.oo_touch_updated_at();

create table if not exists public.oo_purchase_receipts (
  id text primary key,
  store_id text not null references public.oo_stores(id) on delete cascade,
  supplier_id text,
  item_id text not null,
  ingredient_id text references public.oo_ingredients(ingredient_id),
  invoice_no text,
  received_at timestamptz not null,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null,
  total_cost numeric(14,4) not null check (total_cost >= 0),
  currency_code text not null,
  purchase_form text not null default 'as_purchased',
  yield_rate numeric(8,5) check (yield_rate is null or (yield_rate > 0 and yield_rate <= 1)),
  source_url text,
  note text,
  foreign key (store_id, item_id) references public.oo_inventory_items(store_id, item_id) on delete cascade,
  foreign key (store_id, supplier_id) references public.oo_suppliers(store_id, supplier_id) on delete set null
);

create index if not exists oo_purchase_receipts_item_idx on public.oo_purchase_receipts(store_id, item_id, received_at desc);

create table if not exists public.oo_purchase_orders (
  id text primary key,
  store_id text not null references public.oo_stores(id) on delete cascade,
  supplier_id text,
  item_id text not null,
  created_at timestamptz not null,
  expected_at timestamptz,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null,
  estimated_unit_cost numeric(14,4),
  status text not null,
  foreign key (store_id, item_id) references public.oo_inventory_items(store_id, item_id) on delete cascade,
  foreign key (store_id, supplier_id) references public.oo_suppliers(store_id, supplier_id) on delete set null
);

create table if not exists public.oo_inventory_counts (
  id text primary key,
  store_id text not null,
  item_id text not null,
  counted_at timestamptz not null,
  quantity numeric(14,4) not null,
  unit text not null,
  source text not null,
  foreign key (store_id, item_id) references public.oo_inventory_items(store_id, item_id) on delete cascade
);

create table if not exists public.oo_waste_records (
  id text primary key,
  store_id text not null,
  item_id text not null,
  recorded_at timestamptz not null,
  quantity numeric(14,4) not null check (quantity >= 0),
  unit text not null,
  reason text not null,
  worker_id text,
  shift_id text,
  corrective_action text,
  foreign key (store_id, item_id) references public.oo_inventory_items(store_id, item_id) on delete cascade
);

create table if not exists public.oo_prep_items (
  store_id text not null references public.oo_stores(id) on delete cascade,
  prep_id text not null,
  name text not null,
  output_quantity numeric(14,4) not null check (output_quantity > 0),
  output_unit text not null,
  source_url text,
  active boolean not null default true,
  primary key (store_id, prep_id)
);

create table if not exists public.oo_prep_bom (
  id bigint generated by default as identity primary key,
  store_id text not null,
  prep_id text not null,
  item_id text not null,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null,
  line_yield_rate numeric(8,5) check (line_yield_rate is null or (line_yield_rate > 0 and line_yield_rate <= 1)),
  note text,
  foreign key (store_id, prep_id) references public.oo_prep_items(store_id, prep_id) on delete cascade,
  foreign key (store_id, item_id) references public.oo_inventory_items(store_id, item_id) on delete restrict
);

create table if not exists public.oo_menu_items (
  store_id text not null references public.oo_stores(id) on delete cascade,
  menu_item_id text not null,
  name text not null,
  local_name text,
  category text not null,
  concept text,
  selling_price numeric(14,4) not null,
  currency_code text not null,
  waste_buffer_rate numeric(8,5) not null default 0,
  price_basis text,
  menu_source_url text,
  recipe_source_url text,
  benchmark_type text,
  active boolean not null default true,
  primary key (store_id, menu_item_id)
);

create table if not exists public.oo_menu_bom (
  id bigint generated by default as identity primary key,
  store_id text not null,
  menu_item_id text not null,
  component_type text not null check (component_type in ('ingredient','prep')),
  component_id text not null,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null,
  line_yield_rate numeric(8,5) check (line_yield_rate is null or (line_yield_rate > 0 and line_yield_rate <= 1)),
  note text,
  foreign key (store_id, menu_item_id) references public.oo_menu_items(store_id, menu_item_id) on delete cascade
);

-- ---------------------------------------------------------------------------
-- External reference source / raw / normalized cache
-- ---------------------------------------------------------------------------
create table if not exists public.oo_price_sources (
  source_id text primary key,
  label text not null,
  source_kind text not null,
  automation text not null,
  endpoint text,
  source_url text not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.oo_raw_price_observations (
  id uuid primary key default gen_random_uuid(),
  source_id text not null references public.oo_price_sources(source_id),
  market_id text not null,
  fetched_at timestamptz not null default now(),
  observed_at timestamptz,
  request_url text,
  parser_version text,
  status text not null default 'ok',
  error_message text,
  payload jsonb,
  payload_hash text,
  created_at timestamptz not null default now()
);

create index if not exists oo_raw_price_source_market_idx on public.oo_raw_price_observations(source_id, market_id, fetched_at desc);

create table if not exists public.oo_normalized_price_observations (
  id uuid primary key default gen_random_uuid(),
  raw_observation_id uuid references public.oo_raw_price_observations(id) on delete set null,
  source_id text not null references public.oo_price_sources(source_id),
  ingredient_id text references public.oo_ingredients(ingredient_id),
  reference_key text not null,
  market_id text not null,
  geography text,
  price_level text not null,
  original_label text,
  original_price numeric(18,6) not null,
  original_currency text not null,
  original_quantity numeric(18,6) not null,
  original_unit text not null,
  price_per_base_unit numeric(18,8) not null,
  base_unit text not null,
  confidence numeric(5,4) not null default 0.7,
  observed_at timestamptz not null,
  fetched_at timestamptz not null,
  source_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists oo_normalized_price_lookup_idx
on public.oo_normalized_price_observations(market_id, reference_key, observed_at desc, confidence desc);

create table if not exists public.oo_reference_observations (
  id text primary key,
  store_id text references public.oo_stores(id) on delete cascade,
  market_id text not null,
  kind text not null,
  provider text not null,
  reference_key text not null,
  geography text not null,
  observed_at timestamptz not null,
  fetched_at timestamptz not null,
  value jsonb not null,
  unit text,
  currency_code text,
  source_url text,
  freshness text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists oo_reference_lookup_idx on public.oo_reference_observations(market_id, kind, reference_key, observed_at desc);

-- Current market reference: latest, highest-confidence observation for each key.
create or replace view public.oo_latest_reference_prices as
select distinct on (market_id, reference_key)
  id,
  raw_observation_id,
  source_id,
  ingredient_id,
  reference_key,
  market_id,
  geography,
  price_level,
  original_label,
  original_price,
  original_currency,
  original_quantity,
  original_unit,
  price_per_base_unit,
  base_unit,
  confidence,
  observed_at,
  fetched_at,
  source_url,
  metadata
from public.oo_normalized_price_observations
order by market_id, reference_key, observed_at desc, confidence desc, fetched_at desc;

-- Latest store purchase actual, normalized to invoice unit and usable yield.
create or replace view public.oo_latest_store_purchase_costs as
select distinct on (r.store_id, r.item_id)
  r.store_id,
  r.item_id,
  r.ingredient_id,
  r.received_at,
  r.currency_code,
  r.quantity,
  r.unit,
  r.total_cost,
  r.purchase_form,
  coalesce(r.yield_rate, i.store_yield_rate, 1.0) as yield_rate,
  case when r.quantity > 0 then r.total_cost / r.quantity else null end as actual_unit_cost,
  case
    when r.quantity > 0 and coalesce(r.yield_rate, i.store_yield_rate, 1.0) > 0
      then (r.total_cost / r.quantity) / coalesce(r.yield_rate, i.store_yield_rate, 1.0)
    else null
  end as effective_unit_cost
from public.oo_purchase_receipts r
join public.oo_inventory_items i on i.store_id = r.store_id and i.item_id = r.item_id
order by r.store_id, r.item_id, r.received_at desc;

-- ---------------------------------------------------------------------------
-- Seed source registry. Safe to re-run.
-- ---------------------------------------------------------------------------
insert into public.oo_price_sources(source_id, label, source_kind, automation, endpoint, source_url, notes) values
  ('kamis', 'KAMIS Open API', 'official-api', 'configured', 'https://www.kamis.or.kr/service/price/xml.do', 'https://www.kamis.or.kr/customer/reference/openapi_list.do', 'Korea commodity reference; store invoices remain truth.'),
  ('estat-retail-price', 'Japan e-Stat Retail Price Survey', 'official-api', 'configured', 'https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData', 'https://www.e-stat.go.jp/api/index.php/en/api-info/api-spec', 'Tokyo retail benchmark.'),
  ('usda-mmn', 'USDA MyMarketNews', 'official-api', 'configured', 'https://marsapi.ams.usda.gov/services/v1.2/reports', 'https://mymarketnews.ams.usda.gov/mymarketnews-api', 'US wholesale/market reports; explicit report mapping required.'),
  ('eurostat', 'Eurostat Statistics API', 'official-api', 'direct', 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data', 'https://ec.europa.eu/eurostat/web/user-guides/data-browser/api-data-access/api-getting-started/api', 'Macro price index/context, not supplier invoice.'),
  ('mercamadrid', 'Mercamadrid Product Statistics', 'official-download', 'download', 'https://www.mercamadrid.es/estadisticas/', 'https://www.mercamadrid.es/estadisticas/', 'Download/page adapter.'),
  ('shanghai-price-monitor', 'Shanghai Government Food Price Monitoring', 'official-page', 'document', 'https://nyncw.sh.gov.cn/jcsj/index.html', 'https://nyncw.sh.gov.cn/jcsj/index.html', 'Pinned page/file ingestion.'),
  ('open-prices', 'Open Food Facts Open Prices', 'crowdsourced-api', 'direct', 'https://prices.openfoodfacts.org/api/v1/prices', 'https://prices.openfoodfacts.org/api/docs', 'Supplemental retail observations; preserve coverage/confidence.'),
  ('square', 'Square merchant data', 'merchant-api', 'merchant', null, 'https://developer.squareup.com/', 'Future merchant-owned actuals via OAuth.')
on conflict (source_id) do update set
  label = excluded.label,
  source_kind = excluded.source_kind,
  automation = excluded.automation,
  endpoint = excluded.endpoint,
  source_url = excluded.source_url,
  notes = excluded.notes;

-- ---------------------------------------------------------------------------
-- RLS: browser never reads/writes these tables directly in the prototype.
-- Server/service-role access bypasses RLS; future authenticated policies can be added later.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'oo_stores','oo_occupancy_costs','oo_operating_costs','oo_workers',
    'oo_worker_availability_rules','oo_worker_availability_exceptions','oo_shifts',
    'oo_time_entries','oo_incidents','oo_sales_snapshots','oo_sales_items','oo_tasks',
    'oo_store_log','oo_ingredients','oo_ingredient_aliases','oo_yield_benchmarks',
    'oo_suppliers','oo_inventory_items','oo_purchase_receipts','oo_purchase_orders',
    'oo_inventory_counts','oo_waste_records','oo_prep_items','oo_prep_bom','oo_menu_items',
    'oo_menu_bom','oo_price_sources','oo_raw_price_observations',
    'oo_normalized_price_observations','oo_reference_observations'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;
