-- Benchmark/template catalog sourced from the supplied global F&B operating master.
-- These rows are planning/reference templates, never merchant/store actuals.

create table if not exists public.oo_market_planning_profiles (
  market_id text primary key,
  country_name text not null,
  currency_code text not null,
  vat_sales_tax_rate numeric(8,5),
  card_fee_rate numeric(8,5),
  delivery_sales_mix numeric(8,5),
  delivery_commission_rate numeric(8,5),
  monthly_rent_assumption numeric(14,2),
  monthly_utilities_assumption numeric(14,2),
  other_fixed_cost_assumption numeric(14,2),
  legal_wage_floor numeric(14,4),
  wage_unit text,
  wage_source_url text,
  notes text,
  source_dataset text not null default 'fnb-master-2026',
  updated_at timestamptz not null default now()
);

create table if not exists public.oo_ingredient_benchmarks (
  market_id text not null,
  item_id text not null,
  ingredient_name text not null,
  category text not null,
  base_unit text not null,
  procurement_form text not null,
  pack_quantity numeric(18,6) not null,
  pack_price numeric(18,6) not null,
  edible_yield numeric(8,5) not null check (edible_yield > 0 and edible_yield <= 1),
  source_type text,
  source_url text,
  notes text,
  input_status text,
  source_dataset text not null default 'fnb-master-2026',
  updated_at timestamptz not null default now(),
  primary key (market_id, item_id)
);

create table if not exists public.oo_prep_benchmarks (
  market_id text not null,
  prep_id text not null,
  prep_name text not null,
  batch_yield_quantity numeric(18,6) not null,
  output_unit text not null,
  source_url text,
  source_dataset text not null default 'fnb-master-2026',
  primary key (market_id, prep_id)
);

create table if not exists public.oo_prep_benchmark_bom (
  market_id text not null,
  prep_id text not null,
  item_id text not null,
  ingredient_name text,
  quantity numeric(18,6) not null,
  unit text not null,
  source_dataset text not null default 'fnb-master-2026',
  primary key (market_id, prep_id, item_id)
);

create table if not exists public.oo_menu_benchmarks (
  market_id text not null,
  menu_id text not null,
  concept text not null,
  menu_name text not null,
  local_name text,
  currency_code text not null,
  selling_price numeric(18,6) not null,
  price_basis text,
  menu_source_url text,
  recipe_source_url text,
  waste_buffer_rate numeric(8,5),
  benchmark_type text,
  source_dataset text not null default 'fnb-master-2026',
  primary key (market_id, menu_id)
);

create table if not exists public.oo_menu_benchmark_bom (
  market_id text not null,
  menu_id text not null,
  component_type text not null check (component_type in ('ingredient','prep')),
  component_id text not null,
  component_name text,
  quantity numeric(18,6) not null,
  unit text not null,
  source_dataset text not null default 'fnb-master-2026',
  primary key (market_id, menu_id, component_type, component_id)
);

create table if not exists public.oo_labor_templates (
  id bigint generated by default as identity primary key,
  market_id text not null,
  concept text not null,
  role text not null,
  headcount_fte numeric(10,4) not null,
  hours_per_week_per_person numeric(10,4) not null,
  hourly_wage numeric(14,4) not null,
  wage_source_url text,
  source_dataset text not null default 'fnb-master-2026',
  unique (market_id, concept, role)
);

create table if not exists public.oo_reference_menu_qa (
  market_id text not null,
  reference_menu text not null,
  sale_price_krw numeric(18,4),
  declared_cost_krw numeric(18,4),
  declared_food_cost_rate numeric(10,6),
  yield_note text,
  listed_components text,
  component_values text,
  listed_component_sum numeric(18,4),
  difference_from_declared numeric(18,4),
  qa_flag text not null,
  reference_origin text,
  recommended_use text,
  source_dataset text not null default 'user-reference-31',
  primary key (market_id, reference_menu)
);

-- RLS: benchmark tables are server-read/admin-write in the prototype.
do $$
declare
  t text;
begin
  foreach t in array array[
    'oo_market_planning_profiles','oo_ingredient_benchmarks','oo_prep_benchmarks',
    'oo_prep_benchmark_bom','oo_menu_benchmarks','oo_menu_benchmark_bom',
    'oo_labor_templates','oo_reference_menu_qa'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;
